### PR TITLE
make deployment work

### PR DESCRIPTION
**Pull request by kentcdodds**

### CODE REVIEW

**Review by kettanaito — APPROVED** [review]
Looks great. Some jobs are still failing on this PR, is that intentional?

**Comment by kettanaito** [comment]
## Failing CI

The CI fails because the Node.js version we use in the `setup-node` step is v18 while the System Validation automation we have for the workshop requires v20:

```
This computer has node@v18.19.1 installed, but node@>=20 is required. Please update node: https://nodejs.org/
```

**Comment by kettanaito** [comment]
Changed the Node.js version in the `setup-node` action to v20 in 95537a70553297da05708795895628638377e426. Restarting the jobs...

**Comment by kettanaito** [comment]
## Another CI failure

- [Failed job](https://github.com/epicweb-dev/testing-fundamentals/actions/runs/7991109810/job/21821513884?pr=2)

```
> setup:custom
> node ./scripts/setup-custom.js

node:internal/modules/esm/resolve:303
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './apps.server' is not defined by "exports" in /home/runner/work/testing-fundamentals/testing-fundamentals/node_modules/@kentcdodds/workshop-app/package.json imported from /home/runner/work/testing-fundamentals/testing-fundamentals/scripts/setup-custom.js
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at packageResolve (node:internal/modules/esm/resolve:836:14)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Looks like the workshop validation has trouble resolving some modules from `@kentcdodds/workshop-app/package.json`. @kentcdodds can be a missing export issue?

**Comment by kentcdodds** [comment]
Should be fixed now.

**Comment by kentcdodds** [comment]
Failures are unrelated to these changes.

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
Thanks for making this repo better, @kentcdodds!

**Pull request merged**
